//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KillTeam.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KillTeam.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A.
        /// </summary>
        internal static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New Team.
        /// </summary>
        internal static string AddEquipeButton {
            get {
                return ResourceManager.GetString("AddEquipeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add Member.
        /// </summary>
        internal static string AddMembreButton {
            get {
                return ResourceManager.GetString("AddMembreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Team copied in the clipboard.
        /// </summary>
        internal static string AlerteCopier {
            get {
                return ResourceManager.GetString("AlerteCopier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Abilities.
        /// </summary>
        internal static string Aptitudes {
            get {
                return ResourceManager.GetString("Aptitudes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Common abilities throughout faction.
        /// </summary>
        internal static string AptitudesCommunes {
            get {
                return ResourceManager.GetString("AptitudesCommunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Weapon.
        /// </summary>
        internal static string Arme {
            get {
                return ResourceManager.GetString("Arme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Only One Choice Possible.
        /// </summary>
        internal static string ArmeConfigTitle {
            get {
                return ResourceManager.GetString("ArmeConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Required weapons.
        /// </summary>
        internal static string ArmeObligatoireTitle {
            get {
                return ResourceManager.GetString("ArmeObligatoireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Optional Weapons.
        /// </summary>
        internal static string ArmeOptionnelleTitle {
            get {
                return ResourceManager.GetString("ArmeOptionnelleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No Specialty.
        /// </summary>
        internal static string AucuneSpe {
            get {
                return ResourceManager.GetString("AucuneSpe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Flesh wounds.
        /// </summary>
        internal static string Blessures {
            get {
                return ResourceManager.GetString("Blessures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à WS.
        /// </summary>
        internal static string CC {
            get {
                return ResourceManager.GetString("CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ld.
        /// </summary>
        internal static string Cd {
            get {
                return ResourceManager.GetString("Cd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change Weapons.
        /// </summary>
        internal static string ChangeArme {
            get {
                return ResourceManager.GetString("ChangeArme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change Level/Speciality.
        /// </summary>
        internal static string ChangeNiveau {
            get {
                return ResourceManager.GetString("ChangeNiveau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change Specialty.
        /// </summary>
        internal static string ChangeSpe {
            get {
                return ResourceManager.GetString("ChangeSpe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change Trait.
        /// </summary>
        internal static string ChangeTrait {
            get {
                return ResourceManager.GetString("ChangeTrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choice psyker.
        /// </summary>
        internal static string ChoisirPsy {
            get {
                return ResourceManager.GetString("ChoisirPsy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print settings.
        /// </summary>
        internal static string ChoixImpression {
            get {
                return ResourceManager.GetString("ChoixImpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commander.
        /// </summary>
        internal static string Commandant {
            get {
                return ResourceManager.GetString("Commandant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Google Connection.
        /// </summary>
        internal static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Convalescence.
        /// </summary>
        internal static string Convalescence {
            get {
                return ResourceManager.GetString("Convalescence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy.
        /// </summary>
        internal static string Copier {
            get {
                return ResourceManager.GetString("Copier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à BS.
        /// </summary>
        internal static string CT {
            get {
                return ResourceManager.GetString("CT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à D.
        /// </summary>
        internal static string D {
            get {
                return ResourceManager.GetString("D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Google Deconnection.
        /// </summary>
        internal static string Deconnection {
            get {
                return ResourceManager.GetString("Deconnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Details of abilities.
        /// </summary>
        internal static string DetailsAptitudes {
            get {
                return ResourceManager.GetString("DetailsAptitudes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Discipline.
        /// </summary>
        internal static string Discipline {
            get {
                return ResourceManager.GetString("Discipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pdf file cannot be created. Have you accepted corresponding autorisations?.
        /// </summary>
        internal static string DroitFichier {
            get {
                return ResourceManager.GetString("DroitFichier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Duplicate.
        /// </summary>
        internal static string Dupliquer {
            get {
                return ResourceManager.GetString("Dupliquer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à T.
        /// </summary>
        internal static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Errors.
        /// </summary>
        internal static string Erreurs {
            get {
                return ResourceManager.GetString("Erreurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à and.
        /// </summary>
        internal static string Et {
            get {
                return ResourceManager.GetString("Et", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete.
        /// </summary>
        internal static string EtesVousSur {
            get {
                return ResourceManager.GetString("EtesVousSur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Experience.
        /// </summary>
        internal static string Experience {
            get {
                return ResourceManager.GetString("Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à S.
        /// </summary>
        internal static string F {
            get {
                return ResourceManager.GetString("F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Faction.
        /// </summary>
        internal static string Faction {
            get {
                return ResourceManager.GetString("Faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filters.
        /// </summary>
        internal static string Filtres {
            get {
                return ResourceManager.GetString("Filtres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à French.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generate PDF.
        /// </summary>
        internal static string GeneratePDF {
            get {
                return ResourceManager.GetString("GeneratePDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à German.
        /// </summary>
        internal static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In Game.
        /// </summary>
        internal static string InGame {
            get {
                return ResourceManager.GetString("InGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Continue.
        /// </summary>
        internal static string KickStarterContinue {
            get {
                return ResourceManager.GetString("KickStarterContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do not show anymore.
        /// </summary>
        internal static string KickStarterDotNotShow {
            get {
                return ResourceManager.GetString("KickStarterDotNotShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Join us !.
        /// </summary>
        internal static string KickStarterJoinUs {
            get {
                return ResourceManager.GetString("KickStarterJoinUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Meet our new project on Kickstarter : MyMiniReport allows you to create awesome battle report in 4 minutes while playing without interfering your games.
        ///Do you like Kill Team Manager? Help us to create MyMiniReport..
        /// </summary>
        internal static string KickStarterText {
            get {
                return ResourceManager.GetString("KickStarterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Our new app on KickStarter !.
        /// </summary>
        internal static string KickStarterTitle {
            get {
                return ResourceManager.GetString("KickStarterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Abilities list.
        /// </summary>
        internal static string ListAptitudeButton {
            get {
                return ResourceManager.GetString("ListAptitudeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M.
        /// </summary>
        internal static string M {
            get {
                return ResourceManager.GetString("M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à member.
        /// </summary>
        internal static string Membre {
            get {
                return ResourceManager.GetString("Membre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à members.
        /// </summary>
        internal static string Membres {
            get {
                return ResourceManager.GetString("Membres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have several times the same specialist.
        /// </summary>
        internal static string MemeSpe {
            get {
                return ResourceManager.GetString("MemeSpe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Level.
        /// </summary>
        internal static string Niveau {
            get {
                return ResourceManager.GetString("Niveau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        internal static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à no.
        /// </summary>
        internal static string Non {
            get {
                return ResourceManager.GetString("Non", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Model tactics.
        /// </summary>
        internal static string OptionTactiquesDeclinaison {
            get {
                return ResourceManager.GetString("OptionTactiquesDeclinaison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Faction tactics.
        /// </summary>
        internal static string OptionTactiquesFaction {
            get {
                return ResourceManager.GetString("OptionTactiquesFaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à General tactics.
        /// </summary>
        internal static string OptionTactiquesGeneral {
            get {
                return ResourceManager.GetString("OptionTactiquesGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Specialist tactics.
        /// </summary>
        internal static string OptionTactiquesSpecialite {
            get {
                return ResourceManager.GetString("OptionTactiquesSpecialite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à or.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        internal static string Oui {
            get {
                return ResourceManager.GetString("Oui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open.
        /// </summary>
        internal static string Ouvrir {
            get {
                return ResourceManager.GetString("Ouvrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AP.
        /// </summary>
        internal static string PA {
            get {
                return ResourceManager.GetString("PA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shared from Kill Team Manager..
        /// </summary>
        internal static string PartageDepuis {
            get {
                return ResourceManager.GetString("PartageDepuis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Share.
        /// </summary>
        internal static string Partager {
            get {
                return ResourceManager.GetString("Partager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your team does not have a leader.
        /// </summary>
        internal static string PasDeLeader {
            get {
                return ResourceManager.GetString("PasDeLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PDF.
        /// </summary>
        internal static string PDF {
            get {
                return ResourceManager.GetString("PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Official pdf.
        /// </summary>
        internal static string PdfOfficiel {
            get {
                return ResourceManager.GetString("PdfOfficiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phases.
        /// </summary>
        internal static string Phases {
            get {
                return ResourceManager.GetString("Phases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your team is worth more than 100 points.
        /// </summary>
        internal static string PlusDeCentPoints {
            get {
                return ResourceManager.GetString("PlusDeCentPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your team has more than 4 specialists.
        /// </summary>
        internal static string PlusDeQuatreSpe {
            get {
                return ResourceManager.GetString("PlusDeQuatreSpe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your team has more than 20 members.
        /// </summary>
        internal static string PlusDeVingt {
            get {
                return ResourceManager.GetString("PlusDeVingt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Point(s).
        /// </summary>
        internal static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Range.
        /// </summary>
        internal static string Portee {
            get {
                return ResourceManager.GetString("Portee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trait Generalist.
        /// </summary>
        internal static string PouvoirGeneralisteTitle {
            get {
                return ResourceManager.GetString("PouvoirGeneralisteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trait Master Specialist.
        /// </summary>
        internal static string PouvoirMaitreSpeTitle {
            get {
                return ResourceManager.GetString("PouvoirMaitreSpeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} psy power(s) + 1 common in :.
        /// </summary>
        internal static string PsyAuChoix {
            get {
                return ResourceManager.GetString("PsyAuChoix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Psyker.
        /// </summary>
        internal static string Psyker {
            get {
                return ResourceManager.GetString("Psyker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This model can attempt to manifest {0} psychic power(s) and deny {1} psychic power(s) in each Psychic phase..
        /// </summary>
        internal static string PsykerDesc {
            get {
                return ResourceManager.GetString("PsykerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à W.
        /// </summary>
        internal static string PV {
            get {
                return ResourceManager.GetString("PV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New recruit.
        /// </summary>
        internal static string Recrue {
            get {
                return ResourceManager.GetString("Recrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Group identical members.
        /// </summary>
        internal static string RegroupeMembres {
            get {
                return ResourceManager.GetString("RegroupeMembres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Regroup abilities.
        /// </summary>
        internal static string RegrouperAptitudes {
            get {
                return ResourceManager.GetString("RegrouperAptitudes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thanks.
        /// </summary>
        internal static string Remerciement {
            get {
                return ResourceManager.GetString("Remerciement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à replaced with.
        /// </summary>
        internal static string RemplacePar {
            get {
                return ResourceManager.GetString("RemplacePar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Roster.
        /// </summary>
        internal static string Roster {
            get {
                return ResourceManager.GetString("Roster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selection.
        /// </summary>
        internal static string Selection {
            get {
                return ResourceManager.GetString("Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Speciality.
        /// </summary>
        internal static string Specialite {
            get {
                return ResourceManager.GetString("Specialite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        internal static string Supprimer {
            get {
                return ResourceManager.GetString("Supprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sv.
        /// </summary>
        internal static string Sv {
            get {
                return ResourceManager.GetString("Sv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Synchronization.
        /// </summary>
        internal static string Synchro {
            get {
                return ResourceManager.GetString("Synchro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tactics.
        /// </summary>
        internal static string Tactiques {
            get {
                return ResourceManager.GetString("Tactiques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select a speciality.
        /// </summary>
        internal static string TitleSpe {
            get {
                return ResourceManager.GetString("TitleSpe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Too many {0}. ({1} maximum).
        /// </summary>
        internal static string TropDeclinaison {
            get {
                return ResourceManager.GetString("TropDeclinaison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Too many option {0}. ({1} maximum).
        /// </summary>
        internal static string TropRemplacement {
            get {
                return ResourceManager.GetString("TropRemplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can only have one commander.
        /// </summary>
        internal static string UnSeulCommandant {
            get {
                return ResourceManager.GetString("UnSeulCommandant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XP / New recruit / Convalescence.
        /// </summary>
        internal static string XPRecrueConvalescence {
            get {
                return ResourceManager.GetString("XPRecrueConvalescence", resourceCulture);
            }
        }
    }
}
