//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KillTeam.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KillTeam.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Team.
        /// </summary>
        internal static string AddEquipeButton {
            get {
                return ResourceManager.GetString("AddEquipeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Member.
        /// </summary>
        internal static string AddMembreButton {
            get {
                return ResourceManager.GetString("AddMembreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team copied in the clipboard.
        /// </summary>
        internal static string AlerteCopier {
            get {
                return ResourceManager.GetString("AlerteCopier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abilities.
        /// </summary>
        internal static string Aptitudes {
            get {
                return ResourceManager.GetString("Aptitudes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common abilities throughout faction.
        /// </summary>
        internal static string AptitudesCommunes {
            get {
                return ResourceManager.GetString("AptitudesCommunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon.
        /// </summary>
        internal static string Arme {
            get {
                return ResourceManager.GetString("Arme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only One Choice Possible.
        /// </summary>
        internal static string ArmeConfigTitle {
            get {
                return ResourceManager.GetString("ArmeConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required weapons.
        /// </summary>
        internal static string ArmeObligatoireTitle {
            get {
                return ResourceManager.GetString("ArmeObligatoireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional Weapons.
        /// </summary>
        internal static string ArmeOptionnelleTitle {
            get {
                return ResourceManager.GetString("ArmeOptionnelleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Specialty.
        /// </summary>
        internal static string AucuneSpe {
            get {
                return ResourceManager.GetString("AucuneSpe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flesh wounds.
        /// </summary>
        internal static string Blessures {
            get {
                return ResourceManager.GetString("Blessures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WS.
        /// </summary>
        internal static string CC {
            get {
                return ResourceManager.GetString("CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ld.
        /// </summary>
        internal static string Cd {
            get {
                return ResourceManager.GetString("Cd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Weapons.
        /// </summary>
        internal static string ChangeArme {
            get {
                return ResourceManager.GetString("ChangeArme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Level/Speciality.
        /// </summary>
        internal static string ChangeNiveau {
            get {
                return ResourceManager.GetString("ChangeNiveau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Specialty.
        /// </summary>
        internal static string ChangeSpe {
            get {
                return ResourceManager.GetString("ChangeSpe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Trait.
        /// </summary>
        internal static string ChangeTrait {
            get {
                return ResourceManager.GetString("ChangeTrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice psyker.
        /// </summary>
        internal static string ChoisirPsy {
            get {
                return ResourceManager.GetString("ChoisirPsy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print settings.
        /// </summary>
        internal static string ChoixImpression {
            get {
                return ResourceManager.GetString("ChoixImpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commander.
        /// </summary>
        internal static string Commandant {
            get {
                return ResourceManager.GetString("Commandant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Connection.
        /// </summary>
        internal static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convalescence.
        /// </summary>
        internal static string Convalescence {
            get {
                return ResourceManager.GetString("Convalescence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copier {
            get {
                return ResourceManager.GetString("Copier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BS.
        /// </summary>
        internal static string CT {
            get {
                return ResourceManager.GetString("CT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        internal static string D {
            get {
                return ResourceManager.GetString("D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Deconnection.
        /// </summary>
        internal static string Deconnection {
            get {
                return ResourceManager.GetString("Deconnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of abilities.
        /// </summary>
        internal static string DetailsAptitudes {
            get {
                return ResourceManager.GetString("DetailsAptitudes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discipline.
        /// </summary>
        internal static string Discipline {
            get {
                return ResourceManager.GetString("Discipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf file cannot be created. Have you accepted corresponding autorisations?.
        /// </summary>
        internal static string DroitFichier {
            get {
                return ResourceManager.GetString("DroitFichier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        internal static string Dupliquer {
            get {
                return ResourceManager.GetString("Dupliquer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        internal static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        internal static string Erreurs {
            get {
                return ResourceManager.GetString("Erreurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string Et {
            get {
                return ResourceManager.GetString("Et", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete.
        /// </summary>
        internal static string EtesVousSur {
            get {
                return ResourceManager.GetString("EtesVousSur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        internal static string Experience {
            get {
                return ResourceManager.GetString("Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string F {
            get {
                return ResourceManager.GetString("F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faction.
        /// </summary>
        internal static string Faction {
            get {
                return ResourceManager.GetString("Faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string Filtres {
            get {
                return ResourceManager.GetString("Filtres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate PDF.
        /// </summary>
        internal static string GeneratePDF {
            get {
                return ResourceManager.GetString("GeneratePDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Game.
        /// </summary>
        internal static string InGame {
            get {
                return ResourceManager.GetString("InGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string KickStarterContinue {
            get {
                return ResourceManager.GetString("KickStarterContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show anymore.
        /// </summary>
        internal static string KickStarterDotNotShow {
            get {
                return ResourceManager.GetString("KickStarterDotNotShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join us !.
        /// </summary>
        internal static string KickStarterJoinUs {
            get {
                return ResourceManager.GetString("KickStarterJoinUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet our new project on Kickstarter : MyMiniReport allows you to create awesome battle report in 4 minutes while playing without interfering your games.
        ///Do you like Kill Team Manager? Help us to create MyMiniReport..
        /// </summary>
        internal static string KickStarterText {
            get {
                return ResourceManager.GetString("KickStarterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our new app on KickStarter !.
        /// </summary>
        internal static string KickStarterTitle {
            get {
                return ResourceManager.GetString("KickStarterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abilities list.
        /// </summary>
        internal static string ListAptitudeButton {
            get {
                return ResourceManager.GetString("ListAptitudeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        internal static string M {
            get {
                return ResourceManager.GetString("M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to member.
        /// </summary>
        internal static string Membre {
            get {
                return ResourceManager.GetString("Membre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to members.
        /// </summary>
        internal static string Membres {
            get {
                return ResourceManager.GetString("Membres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have several times the same specialist.
        /// </summary>
        internal static string MemeSpe {
            get {
                return ResourceManager.GetString("MemeSpe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string Niveau {
            get {
                return ResourceManager.GetString("Niveau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        internal static string Non {
            get {
                return ResourceManager.GetString("Non", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model tactics.
        /// </summary>
        internal static string OptionTactiquesDeclinaison {
            get {
                return ResourceManager.GetString("OptionTactiquesDeclinaison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faction tactics.
        /// </summary>
        internal static string OptionTactiquesFaction {
            get {
                return ResourceManager.GetString("OptionTactiquesFaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General tactics.
        /// </summary>
        internal static string OptionTactiquesGeneral {
            get {
                return ResourceManager.GetString("OptionTactiquesGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialist tactics.
        /// </summary>
        internal static string OptionTactiquesSpecialite {
            get {
                return ResourceManager.GetString("OptionTactiquesSpecialite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Oui {
            get {
                return ResourceManager.GetString("Oui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Ouvrir {
            get {
                return ResourceManager.GetString("Ouvrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AP.
        /// </summary>
        internal static string PA {
            get {
                return ResourceManager.GetString("PA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared from Kill Team Manager..
        /// </summary>
        internal static string PartageDepuis {
            get {
                return ResourceManager.GetString("PartageDepuis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string Partager {
            get {
                return ResourceManager.GetString("Partager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your team does not have a leader.
        /// </summary>
        internal static string PasDeLeader {
            get {
                return ResourceManager.GetString("PasDeLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        internal static string PDF {
            get {
                return ResourceManager.GetString("PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official pdf.
        /// </summary>
        internal static string PdfOfficiel {
            get {
                return ResourceManager.GetString("PdfOfficiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phases.
        /// </summary>
        internal static string Phases {
            get {
                return ResourceManager.GetString("Phases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your team is worth more than 100 points.
        /// </summary>
        internal static string PlusDeCentPoints {
            get {
                return ResourceManager.GetString("PlusDeCentPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your team has more than 4 specialists.
        /// </summary>
        internal static string PlusDeQuatreSpe {
            get {
                return ResourceManager.GetString("PlusDeQuatreSpe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your team has more than 20 members.
        /// </summary>
        internal static string PlusDeVingt {
            get {
                return ResourceManager.GetString("PlusDeVingt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point(s).
        /// </summary>
        internal static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        internal static string Portee {
            get {
                return ResourceManager.GetString("Portee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trait Generalist.
        /// </summary>
        internal static string PouvoirGeneralisteTitle {
            get {
                return ResourceManager.GetString("PouvoirGeneralisteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trait Master Specialist.
        /// </summary>
        internal static string PouvoirMaitreSpeTitle {
            get {
                return ResourceManager.GetString("PouvoirMaitreSpeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} psy power(s) + 1 common in :.
        /// </summary>
        internal static string PsyAuChoix {
            get {
                return ResourceManager.GetString("PsyAuChoix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psyker.
        /// </summary>
        internal static string Psyker {
            get {
                return ResourceManager.GetString("Psyker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This model can attempt to manifest {0} psychic power(s) and deny {1} psychic power(s) in each Psychic phase..
        /// </summary>
        internal static string PsykerDesc {
            get {
                return ResourceManager.GetString("PsykerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        internal static string PV {
            get {
                return ResourceManager.GetString("PV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New recruit.
        /// </summary>
        internal static string Recrue {
            get {
                return ResourceManager.GetString("Recrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group identical members.
        /// </summary>
        internal static string RegroupeMembres {
            get {
                return ResourceManager.GetString("RegroupeMembres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regroup abilities.
        /// </summary>
        internal static string RegrouperAptitudes {
            get {
                return ResourceManager.GetString("RegrouperAptitudes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks.
        /// </summary>
        internal static string Remerciement {
            get {
                return ResourceManager.GetString("Remerciement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to replaced with.
        /// </summary>
        internal static string RemplacePar {
            get {
                return ResourceManager.GetString("RemplacePar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roster.
        /// </summary>
        internal static string Roster {
            get {
                return ResourceManager.GetString("Roster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        internal static string Selection {
            get {
                return ResourceManager.GetString("Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speciality.
        /// </summary>
        internal static string Specialite {
            get {
                return ResourceManager.GetString("Specialite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Supprimer {
            get {
                return ResourceManager.GetString("Supprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sv.
        /// </summary>
        internal static string Sv {
            get {
                return ResourceManager.GetString("Sv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization.
        /// </summary>
        internal static string Synchro {
            get {
                return ResourceManager.GetString("Synchro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tactics.
        /// </summary>
        internal static string Tactiques {
            get {
                return ResourceManager.GetString("Tactiques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a speciality.
        /// </summary>
        internal static string TitleSpe {
            get {
                return ResourceManager.GetString("TitleSpe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many {0}. ({1} maximum).
        /// </summary>
        internal static string TropDeclinaison {
            get {
                return ResourceManager.GetString("TropDeclinaison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many option {0}. ({1} maximum).
        /// </summary>
        internal static string TropRemplacement {
            get {
                return ResourceManager.GetString("TropRemplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only have one commander.
        /// </summary>
        internal static string UnSeulCommandant {
            get {
                return ResourceManager.GetString("UnSeulCommandant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        internal static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XP / New recruit / Convalescence.
        /// </summary>
        internal static string XPRecrueConvalescence {
            get {
                return ResourceManager.GetString("XPRecrueConvalescence", resourceCulture);
            }
        }
    }
}
