//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KillTeam.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KillTeam.Resx.Translate", typeof(Translate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Team.
        /// </summary>
        internal static string AddEquipeButton {
            get {
                return ResourceManager.GetString("AddEquipeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Member.
        /// </summary>
        internal static string AddMembreButton {
            get {
                return ResourceManager.GetString("AddMembreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only One Choice Possible.
        /// </summary>
        internal static string ArmeConfigTitle {
            get {
                return ResourceManager.GetString("ArmeConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required weapons.
        /// </summary>
        internal static string ArmeObligatoireTitle {
            get {
                return ResourceManager.GetString("ArmeObligatoireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional Weapons.
        /// </summary>
        internal static string ArmeOptionnelleTitle {
            get {
                return ResourceManager.GetString("ArmeOptionnelleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Specialty.
        /// </summary>
        internal static string AucuneSpe {
            get {
                return ResourceManager.GetString("AucuneSpe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Weapons.
        /// </summary>
        internal static string ChangeArme {
            get {
                return ResourceManager.GetString("ChangeArme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Specialty.
        /// </summary>
        internal static string ChangeSpe {
            get {
                return ResourceManager.GetString("ChangeSpe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of abilities.
        /// </summary>
        internal static string DetailsAptitudes {
            get {
                return ResourceManager.GetString("DetailsAptitudes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Aptitudes.
        /// </summary>
        internal static string ListAptitudeButton {
            get {
                return ResourceManager.GetString("ListAptitudeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have several times the same specialist.
        /// </summary>
        internal static string MemeSpe {
            get {
                return ResourceManager.GetString("MemeSpe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your team does not have a leader.
        /// </summary>
        internal static string PasDeLeader {
            get {
                return ResourceManager.GetString("PasDeLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your team is worth more than 100 points.
        /// </summary>
        internal static string PlusDeCentPoints {
            get {
                return ResourceManager.GetString("PlusDeCentPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your team has more than 4 specialists.
        /// </summary>
        internal static string PlusDeQuatreSpe {
            get {
                return ResourceManager.GetString("PlusDeQuatreSpe", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Group identical members.
        /// </summary>
        internal static string RegroupeMembres
        {
            get
            {
                return ResourceManager.GetString("RegroupeMembres", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Group identical members.
        /// </summary>
        internal static string Tactiques
        {
            get
            {
                return ResourceManager.GetString("Tactiques", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Group identical members.
        /// </summary>
        internal static string Erreurs
        {
            get
            {
                return ResourceManager.GetString("Erreurs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Group identical members.
        /// </summary>
        internal static string Copier
        {
            get
            {
                return ResourceManager.GetString("Copier", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Group identical members.
        /// </summary>
        internal static string AlerteCopier
        {
            get
            {
                return ResourceManager.GetString("AlerteCopier", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Group identical members.
        /// </summary>
        internal static string Partager
        {
            get
            {
                return ResourceManager.GetString("Partager", resourceCulture);
            }
        }

        internal static string Arme
        {
            get
            {
                return ResourceManager.GetString("Arme", resourceCulture);
            }
        }

        internal static string Points
        {
            get
            {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }

        internal static string Portee
        {
            get
            {
                return ResourceManager.GetString("Portee", resourceCulture);
            }
        }

        internal static string Type
        {
            get
            {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }

        internal static string F
        {
            get
            {
                return ResourceManager.GetString("F", resourceCulture);
            }
        }

        internal static string PA
        {
            get
            {
                return ResourceManager.GetString("PA", resourceCulture);
            }
        }

        internal static string D
        {
            get
            {
                return ResourceManager.GetString("D", resourceCulture);
            }
        }

        internal static string Aptitudes
        {
            get
            {
                return ResourceManager.GetString("Aptitudes", resourceCulture);
            }
        }

        internal static string M
        {
            get
            {
                return ResourceManager.GetString("M", resourceCulture);
            }
        }

        internal static string CC
        {
            get
            {
                return ResourceManager.GetString("CC", resourceCulture);
            }
        }

        internal static string CT
        {
            get
            {
                return ResourceManager.GetString("CT", resourceCulture);
            }
        }

        internal static string E
        {
            get
            {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }

        internal static string PV
        {
            get
            {
                return ResourceManager.GetString("PV", resourceCulture);
            }
        }

        internal static string A
        {
            get
            {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }

        internal static string Cd
        {
            get
            {
                return ResourceManager.GetString("Cd", resourceCulture);
            }
        }

        internal static string Sv
        {
            get
            {
                return ResourceManager.GetString("Sv", resourceCulture);
            }
        }

        internal static string AptitudesCommunes
        {
            get
            {
                return ResourceManager.GetString("AptitudesCommunes", resourceCulture);
            }
        }

        internal static string Supprimer
        {
            get
            {
                return ResourceManager.GetString("Supprimer", resourceCulture);
            }
        }

        internal static string Roster
        {
            get
            {
                return ResourceManager.GetString("Roster", resourceCulture);
            }
        }

        internal static string Experience
        {
            get
            {
                return ResourceManager.GetString("Experience", resourceCulture);
            }
        }

        internal static string Niveau
        {
            get
            {
                return ResourceManager.GetString("Niveau", resourceCulture);
            }
        }

        internal static string Blessures
        {
            get
            {
                return ResourceManager.GetString("Blessures", resourceCulture);
            }
        }

        internal static string Convalescence
        {
            get
            {
                return ResourceManager.GetString("Convalescence", resourceCulture);
            }
        }

        internal static string Recrue
        {
            get
            {
                return ResourceManager.GetString("Recrue", resourceCulture);
            }
        }

        internal static string Selection
        {
            get
            {
                return ResourceManager.GetString("Selection", resourceCulture);
            }
        }
        internal static string ChangeNiveau
        {
            get
            {
                return ResourceManager.GetString("ChangeNiveau", resourceCulture);
            }
        }

        internal static string TropDeclinaison
        {
            get
            {
                return ResourceManager.GetString("TropDeclinaison", resourceCulture);
            }
        }

        internal static string TropRemplacement
        {
            get
            {
                return ResourceManager.GetString("TropRemplacement", resourceCulture);
            }
        }


        internal static string RemplacePar
        {
            get
            {
                return ResourceManager.GetString("RemplacePar", resourceCulture);
            }
        }

        internal static string Et
        {
            get
            {
                return ResourceManager.GetString("Et", resourceCulture);
            }
        }


        internal static string Or
        {
            get
            {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }

        internal static string TitleSpe
        {
            get
            {
                return ResourceManager.GetString("TitleSpe", resourceCulture);
            }
        }

        internal static string XPRecrueConvalescence
        {
            get
            {
                return ResourceManager.GetString("XPRecrueConvalescence", resourceCulture);
            }
        }

        internal static string PDF
        {
            get
            {
                return ResourceManager.GetString("PDF", resourceCulture);
            }
        }
        internal static string InGame
        {
            get
            {
                return ResourceManager.GetString("InGame", resourceCulture);
            }
        }

        internal static string RegrouperAptitudes
        {
            get
            {
                return ResourceManager.GetString("RegrouperAptitudes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your team has more than 4 specialists.
        /// </summary>
        internal static string PlusDeVingt
        {
            get
            {
                return ResourceManager.GetString("PlusDeVingt", resourceCulture);
            }
        }
        internal static string General
        {
            get
            {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        internal static string Faction
        {
            get
            {
                return ResourceManager.GetString("Faction", resourceCulture);
            }
        }
        internal static string Specialite
        {
            get
            {
                return ResourceManager.GetString("Specialite", resourceCulture);
            }
        }
        internal static string Connection
        {
            get
            {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        internal static string Deconnection
        {
            get
            {
                return ResourceManager.GetString("Deconnection", resourceCulture);
            }
        }
        internal static string PdfOfficiel
        {
            get
            {
                return ResourceManager.GetString("PdfOfficiel", resourceCulture);
            }
        }
        internal static string Synchro
        {
            get
            {
                return ResourceManager.GetString("Synchro", resourceCulture);
            }
        }
        internal static string EtesVousSur
        {
            get
            {
                return ResourceManager.GetString("EtesVousSur", resourceCulture);
            }
        }
        internal static string Oui
        {
            get
            {
                return ResourceManager.GetString("Oui", resourceCulture);
            }
        }
        internal static string Non
        {
            get
            {
                return ResourceManager.GetString("Non", resourceCulture);
            }
        }

        internal static string ChangeTrait
        {
            get
            {
                return ResourceManager.GetString("ChangeTrait", resourceCulture);
            }
        }
        internal static string Commandant
        {
            get
            {
                return ResourceManager.GetString("Commandant", resourceCulture);
            }
        }
        internal static string UnSeulCommandant
        {
            get
            {
                return ResourceManager.GetString("UnSeulCommandant", resourceCulture);
            }
        }
        internal static string ChoisirPsy
        {
            get
            {
                return ResourceManager.GetString("ChoisirPsy", resourceCulture);
            }
        }
        internal static string PsyAuChoix
        {
            get
            {
                return ResourceManager.GetString("PsyAuChoix", resourceCulture);
            }
        }
        internal static string Discipline
        {
            get
            {
                return ResourceManager.GetString("Discipline", resourceCulture);
            }
        }
        internal static string Psyker
        {
            get
            {
                return ResourceManager.GetString("Psyker", resourceCulture);
            }
        }
        internal static string PsykerDesc
        {
            get
            {
                return ResourceManager.GetString("PsykerDesc", resourceCulture);
            }
        }
        internal static string OptionTactiquesGeneral
        {
            get
            {
                return ResourceManager.GetString("OptionTactiquesGeneral", resourceCulture);
            }
        }
        internal static string OptionTactiquesFaction
        {
            get
            {
                return ResourceManager.GetString("OptionTactiquesFaction", resourceCulture);
            }
        }
        internal static string OptionTactiquesSpecialite
        {
            get
            {
                return ResourceManager.GetString("OptionTactiquesSpecialite", resourceCulture);
            }
        }
        internal static string OptionTactiquesDeclinaison
        {
            get
            {
                return ResourceManager.GetString("OptionTactiquesDeclinaison", resourceCulture);
            }
        }
        internal static string Dupliquer
        {
            get
            {
                return ResourceManager.GetString("Dupliquer", resourceCulture);
            }
        }
        internal static string Ouvrir
        {
            get
            {
                return ResourceManager.GetString("Ouvrir", resourceCulture);
            }
        }
        internal static string DroitFichier
        {
            get
            {
                return ResourceManager.GetString("DroitFichier", resourceCulture);
            }
        }
        internal static string French
        {
            get
            {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        internal static string German
        {
            get
            {
                return ResourceManager.GetString("Deutch", resourceCulture);
            }
        }
        internal static string English
        {
            get
            {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        internal static string Language
        {
            get
            {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        internal static string Membres
        {
            get
            {
                return ResourceManager.GetString("Membres", resourceCulture);
            }
        }
        internal static string Remerciement
        {
            get
            {
                return ResourceManager.GetString("Remerciement", resourceCulture);
            }
        }
        internal static string Filtre
        {
            get
            {
                return ResourceManager.GetString("Filtres", resourceCulture);
            }
        }
        internal static string Phases
        {
            get
            {
                return ResourceManager.GetString("Phases", resourceCulture);
            }
        }
        internal static string PartageDepuis
        {
            get
            {
                return ResourceManager.GetString("PartageDepuis", resourceCulture);
            }
        }
        internal static string Membre
        {
            get
            {
                return ResourceManager.GetString("Membre", resourceCulture);
            }
        }

    }

    
}
