
ALTER TABLE Aptitudes ADD COLUMN NomDe TEXT;
ALTER TABLE Aptitudes ADD COLUMN DescriptionDe TEXT;
ALTER TABLE Armes ADD COLUMN NomDe TEXT;
ALTER TABLE Armes ADD COLUMN DescriptionAdditionnelleDe TEXT;
ALTER TABLE Declinaisons ADD COLUMN NomDe TEXT;
ALTER TABLE Factions ADD COLUMN NomDe TEXT;
ALTER TABLE Figurines ADD COLUMN NomDe TEXT;
ALTER TABLE Figurines ADD COLUMN MotClesDe TEXT;
ALTER TABLE Pouvoirs ADD COLUMN NomDe TEXT;
ALTER TABLE Pouvoirs ADD COLUMN DescriptionDe TEXT;
ALTER TABLE ProfileArmes ADD COLUMN NomDe TEXT;
ALTER TABLE ProfileArmes ADD COLUMN AptitudesDe TEXT;
ALTER TABLE Psychiques ADD COLUMN NomDe TEXT;
ALTER TABLE Psychiques ADD COLUMN DescriptionDe TEXT;
ALTER TABLE Specialites ADD COLUMN NomDe TEXT;
ALTER TABLE TypeArmes ADD COLUMN NomDe TEXT;